# Generated by Django 3.2.5 on 2022-05-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='postDate',
            field=models.TextField(default='May 13, 2022'),
        ),
        migrations.AddField(
            model_name='newpost',
            name='postTime',
            field=models.TextField(default='12:27AM'),
        ),
    ]
