# Generated by Django 3.2.5 on 2022-05-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='postDate',
            field=models.TextField(default='May 18, 2022'),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='postTime',
            field=models.TextField(default='12:50PM'),
        ),
    ]
