# Generated by Django 3.2.5 on 2022-05-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220518_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='postTime',
            field=models.TextField(default='12:58PM'),
        ),
    ]
