# Generated by Django 3.2.5 on 2022-05-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220513_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='postTime',
            field=models.TextField(default='07:48PM'),
        ),
    ]
