# Generated by Django 3.2.5 on 2022-05-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_newpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='content',
            field=models.TextField(),
        ),
    ]
