# Generated by Django 3.2.5 on 2022-05-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_newpost_posttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='postTime',
            field=models.TextField(default='02:09PM'),
        ),
    ]
