# Generated by Django 3.2.5 on 2022-05-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_newpost_posttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='postImg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='postTime',
            field=models.TextField(default='10:43PM'),
        ),
    ]
