# Generated by Django 3.2.5 on 2022-05-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220518_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='postTime',
            field=models.TextField(default='02:45PM'),
        ),
    ]
