# Generated by Django 3.2.5 on 2022-05-13 18:29

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220513_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='postImg',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='pic02.jpg', force_format=None, keep_meta=True, null=True, quality=-1, size=[3000, 3000], upload_to=''),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='postTime',
            field=models.TextField(default='11:59PM'),
        ),
    ]
