# Generated by Django 3.2.5 on 2022-05-18 19:55

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220518_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='postDate',
            field=models.TextField(default='May 19, 2022'),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='postImg',
            field=models.ImageField(blank=True, default='pic02.jpg', null=True, storage=djongo.storage.GridFSStorage(base_url='/images/myfiles/', collection='myfiles'), upload_to='images'),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='postTime',
            field=models.TextField(default='01:25AM'),
        ),
    ]
